name: aribn

on:
  schedule:
    - cron: '36 * * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: aribn/rss-to-readme@main
        with:
          feed-url: https://favorites.aribadernatal.com/feed/
          readme-section: feed
